spring.application.name: ereporter

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%5p) %logger : %m%n%wEx"

  level:
    root: WARN
    nl.sling.ereporter: DEBUG

app-incident:
  data-folder: src/test/resources/input
